USE master

CREATE TABLE dbo.TB_CLIENTE
(
    ID_CLIENTE INTEGER PRIMARY KEY IDENTITY NOT NULL,
    DS_NOME VARCHAR(100) NOT NULL
)
GO

CREATE TABLE dbo.TB_TELEFONE
(
    ID_TELEFONE INTEGER PRIMARY KEY IDENTITY NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    NR_DDD INTEGER NOT NULL,
    DS_TELEFONE VARCHAR(10) NOT NULL
)
GO

CREATE TABLE dbo.TB_EMAIL
(
    ID_EMAIL INTEGER PRIMARY KEY IDENTITY NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    DS_EMAIL VARCHAR(200) NOT NULL
)
GO

CREATE TABLE dbo.TB_ENDERECO
(
    ID_ENDERECO INTEGER PRIMARY KEY IDENTITY NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    DS_CEP VARCHAR(9) NOT NULL,
    DS_UF VARCHAR(2) NOT NULL,
    DS_CIDADE VARCHAR(100) NOT NULL,
    DS_BAIRRO VARCHAR(100) NOT NULL,
    DS_LOGRADOURO VARCHAR(100) NOT NULL,
    DS_NUMERO VARCHAR(10) NOT NULL
)
GO

ALTER TABLE dbo.TB_TELEFONE 
ADD CONSTRAINT fkTelefone FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.TB_CLIENTE(ID_CLIENTE)

ALTER TABLE dbo.TB_EMAIL
ADD CONSTRAINT fkEmail FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.TB_CLIENTE(ID_CLIENTE)

ALTER TABLE dbo.TB_ENDERECO 
ADD CONSTRAINT fkEndereco FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.TB_CLIENTE(ID_CLIENTE)

SELECT *
FROM TB_CLIENTE
SELECT *
FROM TB_EMAIL
SELECT *
FROM TB_ENDERECO
SELECT *
FROM TB_TELEFONE